data:
  batch_size: 500
  crop_size: 224
  patch_size: 14
  num_workers: 12
  pin_mem: true
  root_path: ./data_decoder
  is_ubpmc: false
  preserve_aspect_ratio: true
logging:
  folder: ./output
  write_tag: kp-spl-arp
keypoint:
  use_hm_loss: true
  use_aux_heads: true
  hm_slots: 64
  tick_slots: 15
  hm_sigma: 1.0
  class_weights:
  - 0.05
  - 1.0
  - 1.0
meta:
  load_checkpoint: true
  model_name: vit_huge
  decoder_type: simple
  read_checkpoint: model/jepa-arp.pth.tar
  do_finetune: false
  finetune_epoch: 0
  use_bfloat16: true
optimization:
  epochs: 40
  final_lr: 1.0e-05
  final_weight_decay: 0.1
  ipe_scale: 1.0
  lr: 1.0e-03
  start_lr: 2.0e-04
  warmup: 3
  weight_decay: 0.04
