# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#

import math

import torch

from logging import getLogger

logger = getLogger()


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def pack_by_masks(x, batched_masks):
    """
    Packs masked tokens into a padded batch.

    :param x: tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param batched_masks: list of masks, shape [B x [nmasks]]
    :return: tuple of:
        - packed tensor of shape [B * nmasks, L_max, D]
        - attention mask of shape [B * nmasks, L_max] (True for real tokens)
    """
    if len(batched_masks) == 0:
        return x, torch.ones(x.size(0), x.size(1), device=x.device, dtype=torch.bool)

    B, N, D = x.size()
    if len(batched_masks) != B:
        raise ValueError('pack_by_masks expects masks as [B x nmasks]')

    num_masks = len(batched_masks[0])
    if num_masks == 0:
        return x.new_zeros((0, 0, D)), torch.zeros((0, 0), device=x.device, dtype=torch.bool)
    for masks in batched_masks:
        if len(masks) != num_masks:
            raise ValueError('pack_by_masks expects a consistent number of masks per batch')

    def normalize_mask(mask):
        if mask.dtype != torch.bool:
            raise ValueError('pack_by_masks expects boolean masks')
        mask = mask.to(device=x.device).view(-1)
        if mask.numel() < N:
            pad = mask.new_zeros(N - mask.numel())
            mask = torch.cat([mask, pad], dim=0)
        elif mask.numel() > N:
            mask = mask[:N]
        return mask

    mask_tensor = torch.stack(
        [torch.stack([normalize_mask(mask) for mask in masks], dim=0) for masks in batched_masks],
        dim=0
    )  # [B, nmasks, N]

    flat_masks = mask_tensor.reshape(-1, N)  # [B*nmasks, N]
    lengths = flat_masks.sum(dim=1)  # [B*nmasks]
    max_len = int(lengths.max().item()) if lengths.numel() > 0 else 0
    if max_len == 0:
        packed = x.new_zeros((B * num_masks, 0, D))
        attn = torch.zeros((B * num_masks, 0), device=x.device, dtype=torch.bool)
        return packed, attn

    idx = torch.arange(N, device=x.device)
    sort_keys = idx + (~flat_masks).to(idx.dtype) * N
    idx_sorted = sort_keys.argsort(dim=1)

    x_rep = x.repeat_interleave(num_masks, dim=0)
    gather_idx = idx_sorted.unsqueeze(-1).expand(-1, -1, D)
    packed_full = torch.gather(x_rep, 1, gather_idx)

    arange = torch.arange(N, device=x.device)
    attn_full = arange.unsqueeze(0) < lengths.unsqueeze(1)
    packed_full = packed_full * attn_full.unsqueeze(-1)

    return packed_full[:, :max_len], attn_full[:, :max_len]


def repeat_interleave_batch(x, B, repeat):
    """
    This function takes a tensor and repeats it along the batch dimension.
    The batch dimension is assumed to be the first dimension of the tensor.

    :param x: Input tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param B: Original batch size
    :param repeat: Number of times to repeat the tensor along the batch dimension
    :return: Output tensor of shape [B * repeat, N, D]
    """
    N = len(x) // B
    x = torch.cat([
        torch.cat([x[i*B:(i+1)*B] for _ in range(repeat)], dim=0)
        for i in range(N)
    ], dim=0)
    return x
