# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#

import math

import torch

from logging import getLogger

logger = getLogger()


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def apply_masks(x, batched_masks):
    """
    Applies masks to a batch of input sequences.

    :param x: tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param batched_masks: list of masks, shape [B x [nmasks]] or [nmasks x B]
    :return: tensor of shape [B, N, D], where masked patches are zeroed
    """
    if len(batched_masks) == 0:
        return x

    B = x.size(0)
    if isinstance(batched_masks[0], torch.Tensor):
        if len(batched_masks) == B:
            batched_masks = [[mask] for mask in batched_masks]
        else:
            raise ValueError('apply_masks expects masks as [B x nmasks] or [nmasks x B]')

    if len(batched_masks) != B:
        if len(batched_masks[0]) == B:
            num_masks = len(batched_masks)
            batched_masks = [[batched_masks[m][b] for m in range(num_masks)] for b in range(B)]
        else:
            raise ValueError('apply_masks expects masks as [B x nmasks] or [nmasks x B]')

    N = x.size(1)
    mask_union = torch.zeros((B, N), dtype=torch.bool, device=x.device)
    for batch_idx, masks_for_sample in enumerate(batched_masks):
        for mask in masks_for_sample:
            if mask.dtype == torch.bool:
                m_idx = torch.nonzero(mask.view(-1), as_tuple=False).squeeze(1)
            else:
                m_idx = mask.view(-1)
            if m_idx.numel() == 0:
                continue
            mask_union[batch_idx, m_idx] = True

    return x * mask_union.unsqueeze(-1)


def repeat_interleave_batch(x, B, repeat):
    """
    This function takes a tensor and repeats it along the batch dimension.
    The batch dimension is assumed to be the first dimension of the tensor.

    :param x: Input tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param B: Original batch size
    :param repeat: Number of times to repeat the tensor along the batch dimension
    :return: Output tensor of shape [B * repeat, N, D]
    """
    N = len(x) // B
    x = torch.cat([
        torch.cat([x[i*B:(i+1)*B] for _ in range(repeat)], dim=0)
        for i in range(N)
    ], dim=0)
    return x
