# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#

import math

import torch

from logging import getLogger

logger = getLogger()


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def apply_masks(x, batched_masks):
    """
    Applies masks to a batch of input sequences.

    :param x: tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param batched_masks: list of masks, shape [B x [nmasks]]
    :return: tensor of shape [B * nmasks, N, D], where masked patches are zeroed
    """
    if len(batched_masks) == 0:
        return x

    B = x.size(0)
    if len(batched_masks) != B:
        raise ValueError('apply_masks expects masks as [B x nmasks]')

    N = x.size(1)
    all_x = []
    num_masks = len(batched_masks[0])
    for mask_idx in range(num_masks):
        m_val = torch.zeros((B, N), dtype=torch.bool, device=x.device)
        for batch_idx in range(B):
            mask = batched_masks[batch_idx][mask_idx]
            if mask.dtype != torch.bool:
                raise ValueError('apply_masks expects boolean masks')
            mask = mask.view(-1)
            if mask.numel() < N:
                pad = mask.new_zeros(N - mask.numel())
                mask = torch.cat([mask, pad], dim=0)
            elif mask.numel() > N:
                mask = mask[:N]
            m_val[batch_idx] |= mask
        all_x.append(x * m_val.unsqueeze(-1))

    return torch.cat(all_x, dim=0)


def pack_by_masks(x, batched_masks):
    """
    Packs masked tokens into a padded batch.

    :param x: tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param batched_masks: list of masks, shape [B x [nmasks]]
    :return: tuple of:
        - packed tensor of shape [B * nmasks, L_max, D]
        - attention mask of shape [B * nmasks, L_max] (True for real tokens)
    """
    if len(batched_masks) == 0:
        return x, torch.ones(x.size(0), x.size(1), device=x.device, dtype=torch.bool)

    B, N, D = x.size()
    if len(batched_masks) != B:
        raise ValueError('pack_by_masks expects masks as [B x nmasks]')

    num_masks = len(batched_masks[0])
    indices_per_mask = []
    max_len = 0
    for mask_idx in range(num_masks):
        idx_list = []
        for batch_idx in range(B):
            mask = batched_masks[batch_idx][mask_idx]
            if mask.dtype != torch.bool:
                raise ValueError('pack_by_masks expects boolean masks')
            mask = mask.view(-1)
            if mask.numel() < N:
                pad = mask.new_zeros(N - mask.numel())
                mask = torch.cat([mask, pad], dim=0)
            elif mask.numel() > N:
                mask = mask[:N]
            idx = torch.nonzero(mask, as_tuple=False).squeeze(1)
            idx_list.append(idx)
            max_len = max(max_len, idx.numel())
        indices_per_mask.append(idx_list)

    packed = x.new_zeros((B * num_masks, max_len, D))
    attn = torch.zeros((B * num_masks, max_len), device=x.device, dtype=torch.bool)

    for mask_idx, idx_list in enumerate(indices_per_mask):
        for batch_idx, idx in enumerate(idx_list):
            row = mask_idx * B + batch_idx
            if idx.numel() == 0:
                continue
            L = idx.numel()
            packed[row, :L] = x[batch_idx, idx]
            attn[row, :L] = True

    return packed, attn


def repeat_interleave_batch(x, B, repeat):
    """
    This function takes a tensor and repeats it along the batch dimension.
    The batch dimension is assumed to be the first dimension of the tensor.

    :param x: Input tensor of shape [B (batch-size), N (num-patches), D (feature-dim)]
    :param B: Original batch size
    :param repeat: Number of times to repeat the tensor along the batch dimension
    :return: Output tensor of shape [B * repeat, N, D]
    """
    N = len(x) // B
    x = torch.cat([
        torch.cat([x[i*B:(i+1)*B] for _ in range(repeat)], dim=0)
        for i in range(N)
    ], dim=0)
    return x
